# Server Configuration
server.port=8080
spring.application.name=CMFI-Rwanda-Church

# Email Configuration (use environment variable)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cmci.rwanda@gmail.com
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true